spring:
    profiles: dev
name: DEVELOPMENT-YAML
environment: development
servers: 
    - www.abc.test.com
    - www.xyz.test.com
ibm:
    mq:
        queueManager: QM1
        channel: 
        connName:
        user:
        password:
 
---
spring:
    profiles: prod
name: PROD-YAML
environment: production
servers: 
    - www.abc.com
    - www.xyz.com
ibm:
    mq:
        queueManager: QM1
        channel: 
        connName:
        user:
        password:
        